<?php

namespace Sosupp\SlimerBilling\Traits;

use Illuminate\Database\Eloquent\Relations\MorphMany;
use Sosupp\SlimerBilling\Models\BillingItem;

trait Itemable
{
    /**
     * Get all billing items for this model.
     */
    public function billingItems(): MorphMany
    {
        return $this->morphMany(
            config('slimerbilling.models.billing_item', BillingItem::class), 
            'itemable'
        );
    }

    /**
     * Get all billings that include this item.
     */
    public function billings()
    {
        return $this->billingItems()->with('billing')->get()->pluck('billing');
    }

    /**
     * Get total revenue generated by this item.
     */
    public function getTotalRevenueAttribute(): float
    {
        return $this->billingItems()->sum('total');
    }

    /**
     * Get total quantity sold/used.
     */
    public function getTotalQuantityAttribute(): float
    {
        return $this->billingItems()->sum('quantity');
    }

    /**
     * Get average price.
     */
    public function getAveragePriceAttribute(): float
    {
        $count = $this->billingItems()->count();
        if ($count === 0) {
            return 0;
        }
        
        return $this->billingItems()->sum('unit_price') / $count;
    }

    /**
     * Get revenue by date range.
     */
    public function getRevenueForPeriod($startDate, $endDate): float
    {
        return $this->billingItems()
            ->whereHas('billing', function ($query) use ($startDate, $endDate) {
                $query->whereBetween('billing_date', [$startDate, $endDate])
                    ->where('status', 'paid');
            })
            ->sum('total');
    }

    /**
     * Get most recent usage of this item.
     */
    public function getLatestUsage(): ?BillingItem
    {
        return $this->billingItems()
            ->whereHas('billing', function ($query) {
                $query->where('status', 'paid');
            })
            ->latest()
            ->first();
    }

    /**
     * Get usage statistics for this item.
     */
    public function getUsageStatistics(): array
    {
        $stats = $this->billingItems()
            ->selectRaw('
                COUNT(*) as total_uses,
                SUM(quantity) as total_quantity,
                SUM(total) as total_revenue,
                AVG(unit_price) as average_price,
                MAX(unit_price) as max_price,
                MIN(unit_price) as min_price
            ')
            ->first();

        return [
            'total_uses' => (int) ($stats->total_uses ?? 0),
            'total_quantity' => (float) ($stats->total_quantity ?? 0),
            'total_revenue' => (float) ($stats->total_revenue ?? 0),
            'average_price' => (float) ($stats->average_price ?? 0),
            'max_price' => (float) ($stats->max_price ?? 0),
            'min_price' => (float) ($stats->min_price ?? 0),
        ];
    }

    /**
     * Check if this item has been billed.
     */
    public function hasBeenBilled(): bool
    {
        return $this->billingItems()->exists();
    }

    /**
     * Get billings that include this item.
     */
    public function getBillingsWithThisItem()
    {
        return $this->billingItems()->with('billing')->get()->pluck('billing')->unique();
    }

    /**
     * Get quantity used in a specific billing.
     */
    public function getQuantityInBilling(Billing $billing): int
    {
        $item = $this->billingItems()
            ->where('billing_id', $billing->id)
            ->first();
            
        return $item ? $item->quantity : 0;
    }

    /**
     * Get total revenue by status.
     */
    public function getRevenueByStatus(): array
    {
        return $this->billingItems()
            ->join('billings', 'billing_items.billing_id', '=', 'billings.id')
            ->selectRaw('billings.status, SUM(billing_items.total) as total')
            ->groupBy('billings.status')
            ->get()
            ->pluck('total', 'status')
            ->toArray();
    }

    /**
     * Get top billers for this item.
     */
    public function getTopBillers($limit = 10): array
    {
        return $this->billingItems()
            ->join('billings', 'billing_items.billing_id', '=', 'billings.id')
            ->selectRaw('billings.billable_type, billings.billable_id, SUM(billing_items.total) as total_revenue')
            ->groupBy('billings.billable_type', 'billings.billable_id')
            ->orderByDesc('total_revenue')
            ->limit($limit)
            ->get()
            ->toArray();
    }
}